apiVersion: project.jenkins-x.io/v1alpha1
kind: PipelineCatalog
metadata: {}
spec:
  repositories:
  - gitRef: 565b1cec2e3f1fbce6ed7cb570bee3df4906a90b
    gitUrl: https://github.com/jenkins-x/jx3-pipeline-catalog
    label: JX3 Pipeline Catalog
