apiVersion: project.jenkins-x.io/v1alpha1
kind: PipelineCatalog
metadata:
  creationTimestamp: null
spec:
  repositories:
  - gitRef: f9a498d0a91d0183f2acb5a2c5ebe8201c28d2f1
    gitUrl: https://github.com/jenkins-x/jx3-pipeline-catalog
    label: JX3 Pipeline Catalog
