apiVersion: project.jenkins-x.io/v1alpha1
kind: PipelineCatalog
metadata:
  creationTimestamp: null
spec:
  repositories:
  - gitRef: ddb6b90b93020fa09d33a2d2b54a009dfb404159
    gitUrl: https://github.com/jenkins-x/jx3-pipeline-catalog
    label: JX3 Pipeline Catalog
