filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx
repositories:
- name: jxgh
  url: https://jenkins-x-charts.github.io/repo
releases:
- chart: jxgh/jxboot-helmfile-resources
  version: 1.1.524
  name: jxboot-helmfile-resources
  values:
  - ../../versionStream/charts/jxgh/jxboot-helmfile-resources/values.yaml.gotmpl
  - jx-values.yaml
- chart: jxgh/jenkins-x-crds
  version: 3.0.12
  name: jenkins-x-crds
  values:
  - ../../versionStream/charts/jxgh/jenkins-x-crds/values.yaml.gotmpl
  - jx-values.yaml
- chart: jxgh/jx-pipelines-visualizer
  version: 1.8.9
  name: jx-pipelines-visualizer
  values:
  - ../../versionStream/charts/jxgh/jx-pipelines-visualizer/values.yaml.gotmpl
  - jx-values.yaml
- chart: jxgh/jx-preview
  version: 0.5.8
  name: jx-preview
  values:
  - jx-values.yaml
- chart: jxgh/lighthouse
  version: 1.25.0
  name: lighthouse
  values:
  - ../../versionStream/charts/jxgh/lighthouse/values.yaml.gotmpl
  - jx-values.yaml
- chart: jxgh/bucketrepo
  version: 0.6.1
  name: bucketrepo
  values:
  - ../../versionStream/charts/jxgh/bucketrepo/values.yaml.gotmpl
  - jx-values.yaml
- chart: jxgh/jx-build-controller
  version: 0.5.30
  name: jx-build-controller
  values:
  - ../../versionStream/charts/jxgh/jx-build-controller/values.yaml.gotmpl
  - jx-values.yaml
- chart: jxgh/local-external-secrets
  version: 0.0.14
  name: local-external-secrets
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
